version: '3'

services:
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: processor_service
    volumes:
      - .:/processor_service
    ports: 
      - "8000:8000"

  rabbitmq:
    image: rabbitmq:3.6.0-management
    container_name: rabbitmq
    volumes:
      - ./.docker/rabbitmq/etc/:/etc/rabbitmq/
      - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
      - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
    ports:
      - "5672:5672"
      - "15672:15672"

  celery-worker:
    build: .
    command: bash -c "celery -A atlan worker"
    container_name: processor_service
    volumes:
      - .:/processor_service
